"""ITC recovery summary — real, downloadable CSV and PDF built from the merchant's transactions."""
from __future__ import annotations

import csv
from pathlib import Path

import pandas as pd
from fpdf import FPDF

from ..agents.regulatory import DEFAULT_RULE, compute_impact, fee_frame
from ..config import settings
from ..engine.context import MerchantContext
from ..engine.stats import window
from ..formatting import indian_group

DISCLAIMER = (
    "Working summary prepared by Munshi AI from your UPI transaction history. Reconcile against the MDR tax "
    "invoices issued by your payment aggregator before claiming Input Tax Credit in GSTR-3B. Not a tax filing."
)


def _rs(v: float) -> str:
    # PDF core fonts have no Rupee glyph, so PDFs use "Rs."
    return f"Rs. {indian_group(int(round(v)))}" if abs(v) >= 100 else f"Rs. {v:.2f}"


def _affected(ctx: MerchantContext) -> pd.DataFrame:
    fees = window(fee_frame(ctx.tx, DEFAULT_RULE), ctx.as_of, 90)
    return fees[fees["affected"]].sort_values("timestamp")


def _out_dir(ctx: MerchantContext) -> Path:
    d = settings.exports_dir / ctx.merchant_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def itc_csv(ctx: MerchantContext) -> Path:
    rows = _affected(ctx)
    path = _out_dir(ctx) / f"itc_summary_{ctx.merchant_id}_{ctx.as_of:%Y%m%d}.csv"
    with path.open("w", newline="", encoding="utf-8-sig") as f:  # BOM so Excel reads ₹ correctly
        w = csv.writer(f)
        w.writerow(["Munshi AI — ITC recovery summary", ctx.merchant["name"], f"Period: last 90 days to {ctx.as_of - pd.Timedelta(days=1):%d %b %Y}"])
        w.writerow([f"Rule: {DEFAULT_RULE.rate_pct}% MDR (cap ₹{DEFAULT_RULE.cap:.0f}) on P2M UPI > ₹{DEFAULT_RULE.threshold:,.0f}; {DEFAULT_RULE.gst_pct:.0f}% GST on MDR"])
        w.writerow([])
        w.writerow(["date", "transaction_id", "customer_id", "channel", "amount_inr", "mdr_inr", "gst_on_mdr_inr", "cgst_9pct_inr", "sgst_9pct_inr", "itc_claimable_inr"])
        for r in rows.itertuples():
            w.writerow([f"{r.timestamp:%Y-%m-%d}", r.transaction_id, r.customer_id, r.channel, f"{r.amount:.2f}",
                        f"{r.mdr:.2f}", f"{r.gst:.2f}", f"{r.gst / 2:.2f}", f"{r.gst / 2:.2f}", f"{r.gst:.2f}"])
        w.writerow([])
        w.writerow(["TOTAL", "", "", "", f"{rows['amount'].sum():.2f}", f"{rows['mdr'].sum():.2f}", f"{rows['gst'].sum():.2f}",
                    f"{rows['gst'].sum() / 2:.2f}", f"{rows['gst'].sum() / 2:.2f}", f"{rows['gst'].sum():.2f}"])
        w.writerow([])
        w.writerow([DISCLAIMER])
    return path


class _PDF(FPDF):
    def header(self):
        self.set_fill_color(0, 46, 110)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 13)
        self.set_xy(10, 5)
        self.cell(0, 8, "Munshi AI  |  ITC Recovery Summary")
        self.set_text_color(0, 0, 0)
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(110, 110, 110)
        self.cell(0, 6, f"Generated by Munshi AI  -  page {self.page_no()}", align="C")


def itc_pdf(ctx: MerchantContext) -> Path:
    rows = _affected(ctx)
    impact = compute_impact(ctx.tx, ctx.as_of, DEFAULT_RULE)
    retro, fwd = impact["retrospective"], impact["forward_estimate"]
    m = ctx.merchant
    pdf = _PDF()
    pdf.set_auto_page_break(True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, f"{m['name']}  ({m['category']}, {m['city']})", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    period_end = ctx.as_of - pd.Timedelta(days=1)
    pdf.cell(0, 5, f"Merchant ID {m['id']}   |   Period: {period_end - pd.Timedelta(days=89):%d %b %Y} to {period_end:%d %b %Y}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    summary = [
        ("Payments above Rs. 2,000 (one-off, P2M UPI)", f"{retro['affected_transactions']}  ({_rs(retro['affected_value'])})"),
        ("MDR @ 0.4% (cap Rs. 300 / txn)", _rs(retro["mdr"])),
        ("GST @ 18% on MDR  =  ITC claimable", _rs(retro["gst"])),
        ("   of which CGST 9% / SGST 9% (intra-state)", f"{_rs(retro['gst'] / 2)} / {_rs(retro['gst'] / 2)}"),
        ("Net cost to you after ITC", _rs(retro["net_cost_after_itc"])),
        ("Next quarter ITC estimate (range)", f"{_rs(fwd['gross_low'] - fwd['net_low'])} - {_rs(fwd['gross_high'] - fwd['net_high'])}"),
    ]
    for label, value in summary:
        pdf.cell(120, 6, label, border="B")
        pdf.cell(0, 6, value, border="B", align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Month-wise (30-day windows)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 8)
    for h, wdt in (("Window ending", 50), ("Payments", 35), ("MDR", 35), ("GST (ITC)", 35), ("Total", 35)):
        pdf.cell(wdt, 6, h, border=1, align="C")
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    for mo in impact["monthly"]:
        for v, wdt in ((mo["label"], 50), (str(mo["affected_count"]), 35), (_rs(mo["mdr"]), 35), (_rs(mo["gst"]), 35),
                       (_rs(mo["mdr"] + mo["gst"]), 35)):
            pdf.cell(wdt, 5.5, v, border=1, align="C")
        pdf.ln()
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Transaction detail ({len(rows)} payments)", new_x="LMARGIN", new_y="NEXT")
    cols = (("Date", 24), ("Transaction ID", 50), ("Channel", 24), ("Amount", 32), ("MDR", 28), ("GST / ITC", 28))
    pdf.set_font("Helvetica", "B", 8)
    for h, wdt in cols:
        pdf.cell(wdt, 6, h, border=1, align="C")
    pdf.ln()
    pdf.set_font("Helvetica", "", 7.5)
    for r in rows.itertuples():
        vals = (f"{r.timestamp:%d-%m-%Y}", r.transaction_id, r.channel, _rs(r.amount), f"{r.mdr:.2f}", f"{r.gst:.2f}")
        for v, (_, wdt) in zip(vals, cols):
            pdf.cell(wdt, 5, v, border=1, align="C")
        pdf.ln()
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 4.5, DISCLAIMER)

    path = _out_dir(ctx) / f"itc_summary_{ctx.merchant_id}_{ctx.as_of:%Y%m%d}.pdf"
    pdf.output(str(path))
    return path
